#!/bin/bash
source cabecalho
[[ -e /etc/bash.bashrc-bakup ]] && _autorun="\033[1;32m${txt[10]}" || _autorun="\033[1;31m${txt[11]}"
source usercodes 5
echo -e "${cor[1]} \033[0;34m=================================== ${cor[0]}"
echo -e "${cor[2]} [0] □ \033[1;31m[VOLVER / SALIR]"
echo -e "${cor[2]} [1] □${cor[3]} ${txt[5]}"
echo -e "${cor[2]} [2] □${cor[3]} ${txt[6]}"
echo -e "${cor[2]} [3] □${cor[3]} VERIFICAR USUARIOS"
echo -e "${cor[2]} [4] □${cor[3]} ${txt[12]}"
echo -e "${cor[2]} [5] □${cor[3]} INSTALAR WEP"
echo -e "${cor[2]} [6] □${cor[3]} ${txt[20]} $VERIFICAR_PID"
echo -e "${cor[2]} [7] □${cor[3]} ${txt[322]} $_autorun"
echo -e "${cor[2]} [8] □${cor[3]} ${txt[256]}"
echo -e "${cor[2]} [9] □\033[1;31m DESINTALAR SCRIPT"
echo -e "${cor[1]} \033[0;34m===================================  ${cor[0]}"
